"""add type to Activity

Revision ID: 0b15990d7639
Revises: c233392f83e8
Create Date: 2023-05-17 02:13:27.916549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b15990d7639'
down_revision = 'c233392f83e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
