"""add category to Activity

Revision ID: 27e9610109da
Revises: 2c292bf83498
Create Date: 2023-05-17 02:42:32.098315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e9610109da'
down_revision = '2c292bf83498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Category')
    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=1), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=1), nullable=True))
        batch_op.drop_column('category')

    op.create_table('Category',
    sa.Column('categoryActivityID', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['categoryActivityID'], ['Activity.activityID'], ),
    sa.PrimaryKeyConstraint('categoryActivityID', 'category')
    )
    # ### end Alembic commands ###
