"""add activityNam to Activity

Revision ID: 2c292bf83498
Revises: 0b15990d7639
Create Date: 2023-05-17 02:27:08.211363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c292bf83498'
down_revision = '0b15990d7639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activityName', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('intro', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.drop_column('intro')
        batch_op.drop_column('activityName')

    # ### end Alembic commands ###
