"""after discussion 5/18

Revision ID: 54aaa2d2811e
Revises: 27e9610109da
Create Date: 2023-05-20 02:18:36.904191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54aaa2d2811e'
down_revision = '27e9610109da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Hashtag')
    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('peopleLimited', sa.Integer(), nullable=True))
        batch_op.drop_column('activityName')
        batch_op.drop_column('limitedNum')

    with op.batch_alter_table('Participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=1), nullable=True))

    with op.batch_alter_table('Participant', schema=None) as batch_op:
        batch_op.drop_column('score')

    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limitedNum', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('activityName', sa.VARCHAR(length=30), nullable=True))
        batch_op.drop_column('peopleLimited')
        batch_op.drop_column('title')

    op.create_table('Hashtag',
    sa.Column('postID', sa.INTEGER(), nullable=False),
    sa.Column('hashtag', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['postID'], ['Post.postID'], ),
    sa.PrimaryKeyConstraint('postID', 'hashtag')
    )
    # ### end Alembic commands ###
