"""add hostID

Revision ID: c233392f83e8
Revises: 
Create Date: 2023-05-17 01:45:02.003358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c233392f83e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_Activity')
    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hostID', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_Activity_hostID_User'), 'User', ['hostID'], ['userID'])

    with op.batch_alter_table('Participant', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('score')
        batch_op.drop_column('raterUserID')

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_User_nickname'), ['nickname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_User_nickname'), type_='unique')

    with op.batch_alter_table('Participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raterUserID', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('score', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'User', ['raterUserID'], ['userID'])

    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Activity_hostID_User'), type_='foreignkey')
        batch_op.drop_column('hostID')

    op.create_table('_alembic_tmp_Activity',
    sa.Column('activityID', sa.INTEGER(), nullable=False),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.Column('area', sa.VARCHAR(length=1), nullable=True),
    sa.Column('location', sa.VARCHAR(length=30), nullable=True),
    sa.Column('limitedNum', sa.INTEGER(), nullable=True),
    sa.Column('signUp', sa.INTEGER(), nullable=True),
    sa.Column('fee', sa.INTEGER(), nullable=True),
    sa.Column('expireDate', sa.DATE(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=1), nullable=True),
    sa.Column('hostID', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['hostID'], ['User.userID'], ),
    sa.PrimaryKeyConstraint('activityID')
    )
    # ### end Alembic commands ###
